# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            SciFi Coding
tagline:          'AI research'
description:      'AI Reasarch'
url:              "https://scificoding.github.io"
baseurl:          '/'

author:
  name:           'Karim'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/scificoding/scificoding.github.io
